import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: 'antitrust'}],

  lawSidebar: [
    'antitrust/law/overview',
    {
      type: 'category',
      label: 'Concerted Action Among Competitors (Restraints of Trade)',
      link: {
        type: 'doc',
        id: 'antitrust/law/concerted-action-among-competitors',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Emergence of the Rule of Reason',
          link: {
            type: 'doc',
            id: 'antitrust/law/concerted-action-among-competitors/emergence-rule-of-reason',
          },
          collapsed: true,
          items: [
            'antitrust/law/concerted-action-among-competitors/emergence-rule-of-reason/early-common-law',
            'antitrust/law/concerted-action-among-competitors/emergence-rule-of-reason/early-section-1-cases',
            'antitrust/law/concerted-action-among-competitors/emergence-rule-of-reason/development-of-the-rule-of-reason',
            'antitrust/law/concerted-action-among-competitors/emergence-rule-of-reason/development-of-per-se-illegality',
            'antitrust/law/concerted-action-among-competitors/emergence-rule-of-reason/modern-antitrust-analysis',
          ],
        },
        {
          type: 'category',
          label: 'Per Se Analysis',
          link: {
            type: 'doc',
            id: 'antitrust/law/concerted-action-among-competitors/per-se-analysis',
          },
          collapsed: true,
          items: [
            'antitrust/law/concerted-action-among-competitors/per-se-analysis/price-fixing',
            'antitrust/law/concerted-action-among-competitors/per-se-analysis/market-division',
            'antitrust/law/concerted-action-among-competitors/per-se-analysis/group-boycotts',
            'antitrust/law/concerted-action-among-competitors/per-se-analysis/joint-ventures',
          ],
        },
        'antitrust/law/concerted-action-among-competitors/abbreviated-rule-of-reason',
        'antitrust/law/concerted-action-among-competitors/full-rule-of-reason',
      ],
    },
    {
      type: 'category',
      label: 'Distinguishing Concerted from Unilateral Action',
      link: {
        type: 'doc',
        id: 'antitrust/law/distinguishing-concerted-from-unilateral-action',
      },
      collapsed: true,
      items: [
        'antitrust/law/distinguishing-concerted-from-unilateral-action/intra-enterprise-conspiracy-doctrine',
        'antitrust/law/distinguishing-concerted-from-unilateral-action/economics-of-collusion',
        {
          type: 'category',
          label: 'Law of Inferring Agreement',
          link: {
            type: 'doc',
            id: 'antitrust/law/distinguishing-concerted-from-unilateral-action/law-of-inferring-agreement',
          },
          collapsed: true,
          items: [
            'antitrust/law/distinguishing-concerted-from-unilateral-action/law-of-inferring-agreement/inferred-express-and-tacit-agreements',
            'antitrust/law/distinguishing-concerted-from-unilateral-action/law-of-inferring-agreement/agreement-and-summary-procedures',
            'antitrust/law/distinguishing-concerted-from-unilateral-action/law-of-inferring-agreement/identify-who-agreed',
            'antitrust/law/distinguishing-concerted-from-unilateral-action/law-of-inferring-agreement/collective-facilitating-practices',
            'antitrust/law/distinguishing-concerted-from-unilateral-action/law-of-inferring-agreement/unilateral-facilitating-practices',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Politics of the Sherman Act',
      link: {
        type: 'doc',
        id: 'antitrust/law/politics-of-the-sherman-act',
      },
      collapsed: true,
      items: [
        'antitrust/law/politics-of-the-sherman-act/section-1',
        'antitrust/law/politics-of-the-sherman-act/section-2',
      ],
    },
    {
      type: 'category',
      label: 'Exclusionary Conduct (Monopolization)',
      link: {
        type: 'doc',
        id: 'antitrust/law/exclusionary-conduct-monopolization',
      },
      collapsed: true,
      items: [
        'antitrust/law/exclusionary-conduct-monopolization/power-conduct-framework',
        'antitrust/law/exclusionary-conduct-monopolization/market-definition',
        'antitrust/law/exclusionary-conduct-monopolization/non-price-exclusion',
        'antitrust/law/exclusionary-conduct-monopolization/refusals-to-deal',
        'antitrust/law/exclusionary-conduct-monopolization/predatory-pricing',
        'antitrust/law/exclusionary-conduct-monopolization/predatory-bidding',
        'antitrust/law/exclusionary-conduct-monopolization/attempted-monopolization',
        'antitrust/law/exclusionary-conduct-monopolization/remedies',
        'antitrust/law/exclusionary-conduct-monopolization/tying',
        'antitrust/law/exclusionary-conduct-monopolization/exclusive-dealing',
        'antitrust/law/exclusionary-conduct-monopolization/conditional-pricing-practices',
        'antitrust/law/exclusionary-conduct-monopolization/anti-steering-most-favored-nation-clauses',
        'antitrust/law/exclusionary-conduct-monopolization/exclusion-continuum',
        'antitrust/law/exclusionary-conduct-monopolization/concerted-refusals-to-deal',
      ],
    },
    {
      type: 'category',
      label: 'Anticompetitive Distribution Practices',
      link: {
        type: 'doc',
        id: 'antitrust/law/anticompetitive-distribution-practices',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Single-brand restraints',
          link: {
            type: 'doc',
            id: 'antitrust/law/anticompetitive-distribution-practices/single-brand-restraints',
          },
          collapsed: true,
          items: [
            'antitrust/law/anticompetitive-distribution-practices/single-brand-restraints/vertical-within-brand-restraints',
            'antitrust/law/anticompetitive-distribution-practices/single-brand-restraints/exclusive-distributorships',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Mergers and Acquisitions',
      link: {
        type: 'doc',
        id: 'antitrust/law/mergers-and-acquisitions',
      },
      collapsed: true,
      items: [
        'antitrust/law/mergers-and-acquisitions/emergence-and-erosion-of-the-structural-paradigm',
        {
          type: 'category',
          label: 'Horizontal merger analysis under the DOJ/FTC guidelines',
          link: {
            type: 'doc',
            id: 'antitrust/law/mergers-and-acquisitions/horizontal-merger-analysis-under-the-doj-ftc-guidelines',
          },
          collapsed: true,
          items: [
            'antitrust/law/mergers-and-acquisitions/horizontal-merger-analysis-under-the-doj-ftc-guidelines/market-definition',
            'antitrust/law/mergers-and-acquisitions/horizontal-merger-analysis-under-the-doj-ftc-guidelines/market-participants',
            'antitrust/law/mergers-and-acquisitions/horizontal-merger-analysis-under-the-doj-ftc-guidelines/market-concentration',
            {
              type: 'category',
              label: "P's theory of harm",
              link: {
                type: 'doc',
                id: 'antitrust/law/mergers-and-acquisitions/horizontal-merger-analysis-under-the-doj-ftc-guidelines/ps-theory-of-harm',
              },
              collapsed: true,
              items: [
                'antitrust/law/mergers-and-acquisitions/horizontal-merger-analysis-under-the-doj-ftc-guidelines/ps-theory-of-harm/coordinated-competitive-effects',
                'antitrust/law/mergers-and-acquisitions/horizontal-merger-analysis-under-the-doj-ftc-guidelines/ps-theory-of-harm/unilateral-competitive-effects',
              ],
            },
            'antitrust/law/mergers-and-acquisitions/horizontal-merger-analysis-under-the-doj-ftc-guidelines/vertical-mergers-and-conglomerate-mergers',
          ],
        },
        {
          type: 'category',
          label: "D's rebuttals to P's prima facie case",
          link: {
            type: 'doc',
            id: 'antitrust/law/mergers-and-acquisitions/ds-rebuttals-to-ps-prima-facie-case',
          },
          collapsed: true,
          items: [
            'antitrust/law/mergers-and-acquisitions/ds-rebuttals-to-ps-prima-facie-case/entry-and-repositioning',
            'antitrust/law/mergers-and-acquisitions/ds-rebuttals-to-ps-prima-facie-case/procompetitive-efficiencies',
            'antitrust/law/mergers-and-acquisitions/ds-rebuttals-to-ps-prima-facie-case/failing-firms',
          ],
        },
        'antitrust/law/mergers-and-acquisitions/remedies',
      ],
    },
    {
      type: 'category',
      label: 'The Structure of Enforcement',
      link: {
        type: 'doc',
        id: 'antitrust/law/the-structure-of-enforcement',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Private rights of action',
          link: {
            type: 'doc',
            id: 'antitrust/law/the-structure-of-enforcement/private-rights-of-action',
          },
          collapsed: true,
          items: [
            'antitrust/law/the-structure-of-enforcement/private-rights-of-action/statute-of-limitations',
            'antitrust/law/the-structure-of-enforcement/private-rights-of-action/judgments-and-defenses',
            'antitrust/law/the-structure-of-enforcement/private-rights-of-action/antitrust-injury',
          ],
        },
        'antitrust/law/the-structure-of-enforcement/standing',
        'antitrust/law/the-structure-of-enforcement/damages',
        'antitrust/law/the-structure-of-enforcement/antitrust-federalism',
        'antitrust/law/the-structure-of-enforcement/the-first-amendment',
        'antitrust/law/the-structure-of-enforcement/exemptions',
      ],
    },
  ],
  
  economicsSidebar: [{type: 'autogenerated', dirName: 'antitrust/economics'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
};

export default sidebars;
